export default {
  name: "theme",
  title: "Theme",
  type: "document",
  fields: [
    {
      title: "Theme name",
      type: "string",
      name: "name",
    },
    {
      title: "Colors",
      name: "colors",
      type: "object",
      fields: [
        {
          title: "Primary color",
          name: "primary",
          type: "reference",
          to: [{ type: "customColor" }],
        },
        {
          title: "Secondary color",
          name: "secondary",
          type: "reference",
          to: [{ type: "customColor" }],
        },
      ],
    },
    {
      title: "Header",
      name: "header",
      type: "object",
      fields: [
        {
          title: "Header background color",
          name: "backgroundColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Header logo color",
          name: "logoColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Link color",
          description: "The color of the desktop navigation items",
          name: "linkColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Link active color",
          name: "linkActiveColor",
          description: "The color of the active link",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Link hover color",
          name: "linkHoverColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Mobile button burger color",
          name: "mobileButtonBurgerColor",
          description: "Color of the lines on the mobile button",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Mobile button background color",
          name: "mobileButtonBackgroundColor",
          description: "Background color of the mobile button",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
      ],
    },
    {
      title: "Footer",
      name: "footer",
      type: "object",
      fields: [
        {
          title: "Background color",
          name: "backgroundColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Text color",
          name: "textColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
      ],
    },
    {
      title: "Mobile menu",
      name: "mobileMenu",
      type: "object",
      fields: [
        {
          title: "Background color",
          name: "backgroundColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Navigation links color",
          name: "navLinksColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Navigation links hover color",
          name: "navLinksHoverColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
      ],
    },
    {
      title: "Sections",
      name: "sections",
      type: "object",
      fields: [
        {
          title: "Text color",
          name: "textColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Background color",
          name: "backgroundColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Accent color",
          name: "accentColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Link color",
          name: "linkColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Link underline color",
          name: "linkUnderlineColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Link hover color",
          name: "linkHoverColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Controls Color",
          description:
            "The color of the arrow for the previous and next buttons for blocks with navigation such as the carousel block",
          name: "controlsColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Controls Background Color",
          description:
            "The background color of the arrow for the previous and next buttons for blocks with navigation such as the carousel block",
          name: "controlsBackgroundColor",
          type: "reference",
          to: [{ type: "customColor" }],
          validation: (Rule) => Rule.required(),
        },
        {
          title: "Frame Colors",
          description: "Color of the frame lines around media components",
          name: "frameColors",
          type: "array",
          validation: (Rule) => Rule.min(4).max(4),
          of: [
            {
              type: "reference",
              to: [{ type: "customColor" }],
              validation: (Rule) => Rule.required(),
            },
          ],
        },
      ],
    },
  ],
};
