export default [
  { type: "layout" },
  { type: "figure" },
  { type: "showcase" },
  { type: "projectHero" },
  { type: "textContent" },
  { type: "textWithGraphic" },
  { type: "gallery" },
  { type: "linkedGallery" },
  { type: "superImage" },
  { type: "superVideo" },
  { type: "carousel" },
  { type: "linkedCarousel" },
  { type: "statistics" },
  { type: "services" },
  { type: "marquee" },
  { type: "splitText" },
  { type: "instaPost" },
  { type: "grid" },
  { type: "reference", to: [{ type: "section" }] },
  { type: "nextSlug", to: [{ type: "section" }] },
];
