export default [
  { type: "showcase" },
  { type: "projectHero" },
  { type: "superText" },
  { type: "textWithGraphic" },
  { type: "gallery" },
  { type: "linkedGallery" },
  { type: "superImage" },
  { type: "superVideo" },
  { type: "carousel" },
  { type: "linkedCarousel" },
  { type: "statistics" },
  { type: "services" },
  { type: "marquee" },
  { type: "splitText" },
  { type: "instaPost" },
  { type: "nextPage" },
  { type: "reference", to: [{ type: "section" }] },
];
